// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/kcx/v1alpha1.BackupLocation":             schema_pkg_apis_kcx_v1alpha1_BackupLocation(ref),
		"./pkg/apis/kcx/v1alpha1.BackupLocationSpec":         schema_pkg_apis_kcx_v1alpha1_BackupLocationSpec(ref),
		"./pkg/apis/kcx/v1alpha1.BackupLocationStatus":       schema_pkg_apis_kcx_v1alpha1_BackupLocationStatus(ref),
		"./pkg/apis/kcx/v1alpha1.MetadataBackupPolicy":       schema_pkg_apis_kcx_v1alpha1_MetadataBackupPolicy(ref),
		"./pkg/apis/kcx/v1alpha1.MetadataBackupPolicySpec":   schema_pkg_apis_kcx_v1alpha1_MetadataBackupPolicySpec(ref),
		"./pkg/apis/kcx/v1alpha1.MetadataBackupPolicyStatus": schema_pkg_apis_kcx_v1alpha1_MetadataBackupPolicyStatus(ref),
	}
}

func schema_pkg_apis_kcx_v1alpha1_BackupLocation(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "BackupLocation is the Schema for the backuplocations API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/kcx/v1alpha1.BackupLocationSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/kcx/v1alpha1.BackupLocationStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/kcx/v1alpha1.BackupLocationSpec", "./pkg/apis/kcx/v1alpha1.BackupLocationStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_kcx_v1alpha1_BackupLocationSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "BackupLocationSpec defines the desired state of BackupLocation",
				Properties: map[string]spec.Schema{
					"url": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"bucketName": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"credentials": {
						SchemaProps: spec.SchemaProps{
							Description: "name of the secret",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
				Required: []string{"url", "bucketName", "credentials"},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_kcx_v1alpha1_BackupLocationStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "BackupLocationStatus defines the observed state of BackupLocation",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_kcx_v1alpha1_MetadataBackupPolicy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MetadataBackupPolicy is the Schema for the metadatabackuppolicies API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/kcx/v1alpha1.MetadataBackupPolicySpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/kcx/v1alpha1.MetadataBackupPolicyStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/kcx/v1alpha1.MetadataBackupPolicySpec", "./pkg/apis/kcx/v1alpha1.MetadataBackupPolicyStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_kcx_v1alpha1_MetadataBackupPolicySpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MetadataBackupPolicySpec defines the desired state of MetadataBackupPolicy",
				Properties: map[string]spec.Schema{
					"destination": {
						SchemaProps: spec.SchemaProps{
							Description: "Name of the S3 BackupLocation resource",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"certsDir": {
						SchemaProps: spec.SchemaProps{
							Description: "Optional. If not provided, certificates will not be backed up.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"etcdEndpoint": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"etcdCreds": {
						SchemaProps: spec.SchemaProps{
							Description: "Name of the \"secret\" containing etcd certificates.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"schedule": {
						SchemaProps: spec.SchemaProps{
							Description: "The value of this field should be either \"now\" or same as \"schedule\" in \"cronjob\".",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
				Required: []string{"destination", "certsDir", "etcdEndpoint", "etcdCreds", "schedule"},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_kcx_v1alpha1_MetadataBackupPolicyStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MetadataBackupPolicyStatus defines the observed state of MetadataBackupPolicy",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
