# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/kubedr.catalogicsoftware.com_backuplocations.yaml
- bases/kubedr.catalogicsoftware.com_metadatabackuppolicies.yaml
- bases/kubedr.catalogicsoftware.com_metadatabackuprecords.yaml
- bases/kubedr.catalogicsoftware.com_metadatarestores.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# - patches/webhook_in_backuplocations.yaml
# - patches/webhook_in_metadatabackuppolicies.yaml
# - patches/webhook_in_metadatabackuprecords.yaml
#- patches/webhook_in_metadatarestores.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
# - patches/cainjection_in_backuplocations.yaml
# - patches/cainjection_in_metadatabackuppolicies.yaml
# - patches/cainjection_in_metadatabackuprecords.yaml
#- patches/cainjection_in_metadatarestores.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
